package adminkey

import (
	"encoding/hex"
	"testing"
)

// TestKBKDFCompatibility verifies that the Go KBKDF implementation produces
// the same derived key as the Rust aws-lc-rs implementation.
func TestKBKDFCompatibility(t *testing.T) {
	// Use the dev instance secret from convex-backend
	secretStr := "4361726e697461732c206c69746572616c6c79206d65616e696e6720226c6974"
	secret, err := ParseSecret(secretStr)
	if err != nil {
		t.Fatalf("ParseSecret() error = %v", err)
	}

	// Derive the key using the same purpose as admin key generation
	derivedKey := kbkdfCTRHMAC(secret[:], []byte(purposeAdminKey), keyLen)
	derivedKeyHex := hex.EncodeToString(derivedKey)

	// This expected value was generated by the Rust aws-lc-rs implementation:
	// Rust KBKDF derived key: a7526e1715ea4effa55636bee910d731
	expectedKey := "a7526e1715ea4effa55636bee910d731"

	if derivedKeyHex != expectedKey {
		t.Errorf("KBKDF derived key mismatch:\n  got:      %s\n  expected: %s", derivedKeyHex, expectedKey)
	}
}
